-- SQL schema for cursos table

CREATE TABLE IF NOT EXISTS `cursos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT DEFAULT NULL,
  `miniatura` VARCHAR(512) DEFAULT NULL,
  `banner` VARCHAR(512) DEFAULT NULL,
  `link` VARCHAR(512) DEFAULT NULL,
  `selo` VARCHAR(100) DEFAULT NULL,
  `imagens` JSON DEFAULT NULL,
  `criado_em` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
